Create Cell basics sample
WildernessLabs/Meadow.Core.Samples pull request #80
Opened 2023-08-24 17:02 UTC by duduita

2023-08-24 17:16 UTC, halyssonJr approved these changes

2023-09-05 21:26 UTC, jorgedevs requested changes

2023-09-05 21:26 UTC, jorgedevs commented on Source/Meadow.Core.Samples/Network/Cell_Basics/Cell_Basics.csproj
> +    <PackageReference Include="Meadow.F7" Version="0.*" />
Change version to `Version="0.*"`, otherwise, it'll pick up the last version before we went 1.0

2023-09-05 21:29 UTC, jorgedevs approved these changes

2023-09-05 22:00 UTC, merged